### ISSUE TITLE
3 column edge case

### ISSUE THREAD

**Issue by deathau** [deathau/maximise-active-pane-obsidian#2]
> I've noticed an edge case that doesn't seem to work.  I currently have 3 panes open side by side with a single document in the left column, 2 documents in the middle column (one on top of the other) and a single document in the third column (see first screenshot below).  Maximising works great for all notes except the one in the 3rd column. The result of maximising the third column is shown in the second screenshot below.  Is there a way around this ?  I don't have any custom CSS applied.
![unknown](https://user-images.githubusercontent.com/1421840/102131105-d3456b00-3ea5-11eb-9ef4-9018c6e668a2.png)
![unknown-1](https://user-images.githubusercontent.com/1421840/102131122-da6c7900-3ea5-11eb-9ab6-22b57461fa7a.png)

**Comment by gala8y** [comment]
I can confirm, it does not work on all notes when window is split both vertically and horizontally (more then two notes) in various configurations. At least one note can not be maximized (other notes are getting hidden, but size of note to be maximized stays the same).

**Comment by alanscodelog** [comment]
Ran into a similar problem. I have three horizontally split panes to the left and one large pane to the right. As a workaround added this to my css:
```css
.maximised .workspace-leaf.mod-active {
   flex-basis: calc(100% - 4px) !important; /* 4px is for scrollbar width */
}
```

**Comment by gala8y** [comment]
hi again ;) i still get problems maximizing note sometimes -  there is a special set up of notes (window split both horizontally and vertically), which breaks maximizing. its seems like T divisions are fine, but any 'cross' division, even if arms of cross are not aligned (not starting from one point), breaks it all.
please see screens, its kinda hard to catch any rules here:

this works (all notes maximize fine):
![image](https://user-images.githubusercontent.com/1263605/104768985-d9fa2300-576e-11eb-8b33-920832cfa464.png)

adding this breaks maximizing of all notes...
![image](https://user-images.githubusercontent.com/1263605/104769020-ea120280-576e-11eb-9c8f-57f1561fed03.png)

... like this...
![image](https://user-images.githubusercontent.com/1263605/104769047-f39b6a80-576e-11eb-8cbe-c94b460a34b6.png)

... like this.
![image](https://user-images.githubusercontent.com/1263605/104769055-f72ef180-576e-11eb-8165-cd1f03d28960.png)

**Comment by alanscodelog** [comment]
Can confirm this. I didn't realize it at first but obsidian nests the splits making it really hard to implement something like this that always works. The only workaround I could find that does work all the time requires position fixed, but this means you cannot open the left side panel (you can sort of have the right one work). Alternatively, right/left could be set to 0 and the panels are never visible (this is what I'm personally doing since I use this mode when I want to take notes in a corner of the screen)

```css
.maximised .workspace-leaf.mod-active {
    position: fixed;
    top: 22px; /* title bar height */
    left: 30px; /* show left panel ribbon, but you won't be able to open */
    right: 30px; /* show right panel ribbon */
    bottom: 0;
    width: calc(100% - 60px); /* can just be 100% if you set right/left 0 */
    height: 100%;
    z-index: 16; /* 15 is the panel borders */
}

/* make right panel be above the maximized panel - this cannot be used/reversed for
the left panel due to how sibling selectors work, someday attr() will save us but
currently no browser supports it for numbers */
.workspace > .maximised ~ .workspace-split:last-of-type {
	z-index:17;
}
```

A css only fix would required that the maximized class be one level above so we can do `.maximised .workspace-split:last/first-of-type` and set the side panels above anytime we maximize. Am not familiar with obsidian's api so don't know how possible this is.

This does change the way the panels work though. A fix true to the original intention of the plugin would require watching the side pabels for width changes and applying those changes to the maximized panel via js which I have no idea how possible that is.
